<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JarkomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('jarkoms')->insert(array(        
        array(
            'nim'               => "1844190003",
            'sistem_tekinf'     => 80,
            'jarkom'            => 68,
            'prak_jarkom'       => 72,
            'sistem_digital'    => 78,
            'aok'               => 83,
            'keamanan_info'     => 68,
            'jumlah'            => 449,
            'created_at'        => date("Y-m-d h:i:s"),
            'updated_at'        => date("Y-m-d h:i:s"),
        ),
        array(
            'nim'               => "1844190007",
            'sistem_tekinf'     => 80,
            'jarkom'            => 83,
            'prak_jarkom'       => 71,
            'sistem_digital'    => 80,
            'aok'               => 81,
            'keamanan_info'     => 55,
            'jumlah'            => 450,  
            'created_at'        => date("Y-m-d h:i:s"),
            'updated_at'        => date("Y-m-d h:i:s"),
        ),
        array(
            'nim'               => "1844190010",
            'sistem_tekinf'     => 81,
            'jarkom'            => 78,
            'prak_jarkom'       => 74,
            'sistem_digital'    => 76,
            'aok'               => 78,
            'keamanan_info'     => 83,
            'jumlah'            => 470,  
            'created_at'        => date("Y-m-d h:i:s"),
            'updated_at'        => date("Y-m-d h:i:s"),
        ),
        array(
            'nim'               => "1844190021",
            'sistem_tekinf'     => 90,
            'jarkom'            => 84,
            'prak_jarkom'       => 83,
            'sistem_digital'    => 77,
            'aok'               => 80,
            'keamanan_info'     => 81,
            'jumlah'            => 495,  
            'created_at'        => date("Y-m-d h:i:s"),
            'updated_at'        => date("Y-m-d h:i:s"),
        ),
        array(
            'nim'               => "1844190025",
            'sistem_tekinf'     => 81,
            'jarkom'            => 89,
            'prak_jarkom'       => 86,
            'sistem_digital'    => 78,
            'aok'               => 79,
            'keamanan_info'     => 85,
            'jumlah'            => 498,  
            'created_at'        => date("Y-m-d h:i:s"),
            'updated_at'        => date("Y-m-d h:i:s"),
        ),
        array(
            'nim'               => "1844190026",
            'sistem_tekinf'     => 81,
            'jarkom'            => 80,
            'prak_jarkom'       => 81,
            'sistem_digital'    => 80,
            'aok'               => 77,
            'keamanan_info'     => 81,
            'jumlah'            => 480,  
            'created_at'        => date("Y-m-d h:i:s"),
            'updated_at'        => date("Y-m-d h:i:s"),
        ),
        array(
            'nim'               => "1844190029",
            'sistem_tekinf'     => 82,
            'jarkom'            => 78,
            'prak_jarkom'       => 78,
            'sistem_digital'    => 78,
            'aok'               => 77,
            'keamanan_info'     => 76,
            'jumlah'            => 469,  
            'created_at'        => date("Y-m-d h:i:s"),
            'updated_at'        => date("Y-m-d h:i:s"),
        ),
        array(
            'nim'               => "1844190036",
            'sistem_tekinf'     => 81,
            'jarkom'            => 74,
            'prak_jarkom'       => 80,
            'sistem_digital'    => 85,
            'aok'               => 76,
            'keamanan_info'     => 83,
            'jumlah'            => 479,  
            'created_at'        => date("Y-m-d h:i:s"),
            'updated_at'        => date("Y-m-d h:i:s"),
        ),
        array(
            'nim'               => "1844190042",
            'sistem_tekinf'     => 80,
            'jarkom'            => 80,
            'prak_jarkom'       => 74,
            'sistem_digital'    => 74,
            'aok'               => 81,
            'keamanan_info'     => 70,
            'jumlah'            => 459,  
            'created_at'        => date("Y-m-d h:i:s"),
            'updated_at'        => date("Y-m-d h:i:s"),
        ),
        array(
            'nim'               => "1844190049",
            'sistem_tekinf'     => 83,
            'jarkom'            => 90,
            'prak_jarkom'       => 76,
            'sistem_digital'    => 85,
            'aok'               => 77,
            'keamanan_info'     => 84,
            'jumlah'            => 495,  
            'created_at'        => date("Y-m-d h:i:s"),
            'updated_at'        => date("Y-m-d h:i:s"),
        ),
        array(
            'nim'               => "1844190053",
            'sistem_tekinf'     => 81,
            'jarkom'            => 79,
            'prak_jarkom'       => 76,
            'sistem_digital'    => 81,
            'aok'               => 79,
            'keamanan_info'     => 78,
            'jumlah'            => 474,  
            'created_at'        => date("Y-m-d h:i:s"),
            'updated_at'        => date("Y-m-d h:i:s"),
        ),
        array(
            'nim'               => "1844190054",
            'sistem_tekinf'     => 82,
            'jarkom'            => 82,
            'prak_jarkom'       => 77,
            'sistem_digital'    => 72,
            'aok'               => 79,
            'keamanan_info'     => 82,
            'jumlah'            => 474,  
            'created_at'        => date("Y-m-d h:i:s"),
            'updated_at'        => date("Y-m-d h:i:s"),
        ),
        array(
            'nim'               => "1844190055",
            'sistem_tekinf'     => 80,
            'jarkom'            => 86,
            'prak_jarkom'       => 82,
            'sistem_digital'    => 84,
            'aok'               => 83,
            'keamanan_info'     => 88,
            'jumlah'            => 503,  
            'created_at'        => date("Y-m-d h:i:s"),
            'updated_at'        => date("Y-m-d h:i:s"),
        ),
        array(
            'nim'               => "1844190056",
            'sistem_tekinf'     => 80,
            'jarkom'            => 81,
            'prak_jarkom'       => 74,
            'sistem_digital'    => 79,
            'aok'               => 83,
            'keamanan_info'     => 78,
            'jumlah'            => 475,  
            'created_at'        => date("Y-m-d h:i:s"),
            'updated_at'        => date("Y-m-d h:i:s"),
        )
        ));
    }
}         
