<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KwcSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('kwcs')->insert(array(
            array(
                'nim'               => "1844190003",
                'data_mining'       => 73,
                'tekweb'            => 87,
                'prak_tekweb'       => 56,
                'sda'               => 67,
                'prak_sda'          => 68,
                'dasar_algoritma'   => 77,
                'jumlah'            => 428,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190007",
                'data_mining'       => 64,
                'tekweb'            => 91,
                'prak_tekweb'       => 72,
                'sda'               => 67,
                'prak_sda'          => 71,
                'dasar_algoritma'   => 75,
                'jumlah'            => 440,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190010",
                'data_mining'       => 76,
                'tekweb'            => 83,
                'prak_tekweb'       => 71,
                'sda'               => 65,
                'prak_sda'          => 79,
                'dasar_algoritma'   => 79,
                'jumlah'            => 453,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190021",
                'data_mining'       => 70,
                'tekweb'            => 92,
                'prak_tekweb'       => 65,
                'sda'               => 65,
                'prak_sda'          => 74,
                'dasar_algoritma'   => 72,
                'jumlah'            => 438,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190025",
                'data_mining'       => 76,
                'tekweb'            => 87,
                'prak_tekweb'       => 65,
                'sda'               => 79,
                'prak_sda'          => 80,
                'dasar_algoritma'   => 69,
                'jumlah'            => 456,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190026",
                'data_mining'       => 77,
                'tekweb'            => 86,
                'prak_tekweb'       => 72,
                'sda'               => 76,
                'prak_sda'          => 83,
                'dasar_algoritma'   => 72,
                'jumlah'            => 466,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190029",
                'data_mining'       => 74,
                'tekweb'            => 92,
                'prak_tekweb'       => 69,
                'sda'               => 74,
                'prak_sda'          => 70,
                'dasar_algoritma'   => 69,
                'jumlah'            => 448,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190036",
                'data_mining'       => 87,
                'tekweb'            => 93,
                'prak_tekweb'       => 82,
                'sda'               => 92,
                'prak_sda'          => 95,
                'dasar_algoritma'   => 78,
                'jumlah'            => 527,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190042",
                'data_mining'       => 71,
                'tekweb'            => 86,
                'prak_tekweb'       => 74,
                'sda'               => 71,
                'prak_sda'          => 78,
                'dasar_algoritma'   => 71,
                'jumlah'            => 451,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190049",
                'data_mining'       => 75,
                'tekweb'            => 93,
                'prak_tekweb'       => 82,
                'sda'               => 90,
                'prak_sda'          => 80,
                'dasar_algoritma'   => 79,
                'jumlah'            => 499,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190053",
                'data_mining'       => 71,
                'tekweb'            => 64,
                'prak_tekweb'       => 62,
                'sda'               => 66,
                'prak_sda'          => 68,
                'dasar_algoritma'   => 77,
                'jumlah'            => 408,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190054",
                'data_mining'       => 83,
                'tekweb'            => 81,
                'prak_tekweb'       => 90,
                'sda'               => 79,
                'prak_sda'          => 75,
                'dasar_algoritma'   => 72,
                'jumlah'            => 480,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190055",
                'data_mining'       => 84,
                'tekweb'            => 95,
                'prak_tekweb'       => 78,
                'sda'               => 86,
                'prak_sda'          => 73,
                'dasar_algoritma'   => 79,
                'jumlah'            => 495,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190056",
                'data_mining'       => 59,
                'tekweb'            => 75,
                'prak_tekweb'       => 53,
                'sda'               => 77,
                'prak_sda'          => 73,
                'dasar_algoritma'   => 75,
                'jumlah'            => 412,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
        ));
    }
}