<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RplSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('rpls')->insert(array(
            array(
                'nim'               => "1844190003",
                'ddp'               => 78,
                'prak_ddp'          => 79,
                'prak_basdat'       => 80,
                'basdat'            => 66,
                'pbo'               => 67,
                'prak_pbo'          => 68,
                'rpl'               => 80,
                'basdat_lanjut'     => 78,
                'pem_visual'        => 65,
                'aps'               => 82,
                'tbo'               => 77,
                'jumlah'            => 820,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190007",
                'ddp'               => 69,
                'prak_ddp'          => 75,
                'prak_basdat'       => 78,
                'basdat'            => 66,
                'pbo'               => 78,
                'prak_pbo'          => 74,
                'rpl'               => 77,
                'basdat_lanjut'     => 77,
                'pem_visual'        => 68,
                'aps'               => 80,
                'tbo'               => 86,
                'jumlah'            => 828,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190010",
                'ddp'               => 73,
                'prak_ddp'          => 74,
                'prak_basdat'       => 76,
                'basdat'            => 64,
                'pbo'               => 81,
                'prak_pbo'          => 79,
                'rpl'               => 81,
                'basdat_lanjut'     => 84,
                'pem_visual'        => 66,
                'aps'               => 81,
                'tbo'               => 81,
                'jumlah'            => 840,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190021",
                'ddp'               => 77,
                'prak_ddp'          => 79,
                'prak_basdat'       => 81,
                'basdat'            => 75,
                'pbo'               => 69,
                'prak_pbo'          => 67,
                'rpl'               => 81,
                'basdat_lanjut'     => 74,
                'pem_visual'        => 70,
                'aps'               => 79,
                'tbo'               => 83,
                'jumlah'            => 835,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190025",
                'ddp'               => 84,
                'prak_ddp'          => 79,
                'prak_basdat'       => 84,
                'basdat'            => 68,
                'pbo'               => 76,
                'prak_pbo'          => 68,
                'rpl'               => 77,
                'basdat_lanjut'     => 84,
                'pem_visual'        => 68,
                'aps'               => 74,
                'tbo'               => 81,
                'jumlah'            => 843,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190026",
                'ddp'               => 82,
                'prak_ddp'          => 78,
                'prak_basdat'       => 80,
                'basdat'            => 70,
                'pbo'               => 75,
                'prak_pbo'          => 78,
                'rpl'               => 83,
                'basdat_lanjut'     => 79,
                'pem_visual'        => 73,
                'aps'               => 77,
                'tbo'               => 76,
                'jumlah'            => 851,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190029",
                'ddp'               => 72,
                'prak_ddp'          => 84,
                'prak_basdat'       => 82,
                'basdat'            => 64,
                'pbo'               => 74,
                'prak_pbo'          => 76,
                'rpl'               => 78,
                'basdat_lanjut'     => 77,
                'pem_visual'        => 75,
                'aps'               => 79,
                'tbo'               => 79,
                'jumlah'            => 840,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190036",
                'ddp'               => 88,
                'prak_ddp'          => 84,
                'prak_basdat'       => 87,
                'basdat'            => 79,
                'pbo'               => 79,
                'prak_pbo'          => 70,
                'rpl'               => 85,
                'basdat_lanjut'     => 85,
                'pem_visual'        => 89,
                'aps'               => 80,
                'tbo'               => 79,
                'jumlah'            => 905,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190042",
                'ddp'               => 74,
                'prak_ddp'          => 94,
                'prak_basdat'       => 83,
                'basdat'            => 61,
                'pbo'               => 80,
                'prak_pbo'          => 87,
                'rpl'               => 79,
                'basdat_lanjut'     => 74,
                'pem_visual'        => 84,
                'aps'               => 75,
                'tbo'               => 85,
                'jumlah'            => 876,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190049",
                'ddp'               => 84,
                'prak_ddp'          => 82,
                'prak_basdat'       => 87,
                'basdat'            => 72,
                'pbo'               => 91,
                'prak_pbo'          => 87,
                'rpl'               => 85,
                'basdat_lanjut'     => 89,
                'pem_visual'        => 85,
                'aps'               => 85,
                'tbo'               => 88,
                'jumlah'            => 935,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190053",
                'ddp'               => 85,
                'prak_ddp'          => 80,
                'prak_basdat'       => 78,
                'basdat'            => 65,
                'pbo'               => 71,
                'prak_pbo'          => 70,
                'rpl'               => 77,
                'basdat_lanjut'     => 81,
                'pem_visual'        => 71,
                'aps'               => 77,
                'tbo'               => 80,
                'jumlah'            => 835,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190054",
                'ddp'               => 91,
                'prak_ddp'          => 82,
                'prak_basdat'       => 83,
                'basdat'            => 69,
                'pbo'               => 84,
                'prak_pbo'          => 82,
                'rpl'               => 82,
                'basdat_lanjut'     => 84,
                'pem_visual'        => 75,
                'aps'               => 83,
                'tbo'               => 88,
                'jumlah'            => 903,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190055",
                'ddp'               => 87,
                'prak_ddp'          => 82,
                'prak_basdat'       => 85,
                'basdat'            => 65,
                'pbo'               => 81,
                'prak_pbo'          => 78,
                'rpl'               => 83,
                'basdat_lanjut'     => 82,
                'pem_visual'        => 82,
                'aps'               => 78,
                'tbo'               => 87,
                'jumlah'            => 890,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
            array(
                'nim'               => "1844190056",
                'ddp'               => 82,
                'prak_ddp'          => 71,
                'prak_basdat'       => 78,
                'basdat'            => 60,
                'pbo'               => 66,
                'prak_pbo'          => 63,
                'rpl'               => 65,
                'basdat_lanjut'     => 81,
                'pem_visual'        => 64,
                'aps'               => 75,
                'tbo'               => 70,
                'jumlah'            => 775,
                'created_at'        => date("Y-m-d h:i:s"),
                'updated_at'        => date("Y-m-d h:i:s"),
            ),
        ));
    }
}
